server:
    port: 8080
spring:
    application:
        name: Rental-Unit-Management

    # datasource:
    #     url: jdbc:h2:mem:mydb
    #     username: root
    #     password: pooltask1
    #     driverClassName: org.h2.Driver
    # jpa:
    #     database-platform: org.hibernate.dialect.H2Dialect
    #     hibernate:
    #         ddl-auto: update
            
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        username: ${POSTGRES_USERNAME}
        url: ${POSTGRES_URL}
        
    jpa:
        hibernate:
            ddl-auto: update
            dialect: PostgreSQLDialect
        
logging:
    level:
        org.springframework.security: INFO
        root: INFO
        org:
            springframework:
            web:
                servlet:
                org.springframework.web.servlet.DispatcherServlet: INFO
jwt:
    secret: ${jwtSecret}
initUser:
    email:  ${INIT_EMAIL}
    password:   ${INIT_PASSWORD}
mail:
    originmail: 




