server:
  port: 8080

spring:
  application:
    name: Rental-Unit-Management
  datasource:
    url: jdbc:h2:./mem/rentalsdb
    username: root
    password: pooltask1
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: INFO
    root: INFO
    org:
      springframework:
      web:
        servlet:
        org.springframework.web.servlet.DispatcherServlet: INFO
jwt:
  secret: Wz84KgeHl2vA5CwRT82l5XvtRLOlc8oZx2um1VoZDIc=

springdoc:
  swagger-ui:
    tagsSorter: alpha

mail:
  origin:
#    host:
#    port:
#    origin:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
